# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c77e226d45399d74c3c142a2a4903da71f701fdf7bc42fdc02826b1203cf07270ef045193f8809c3cf81e009256eae64e281fb9a7048cfc7fb3aa31f0c23887

test:
  secret_key_base: 5dff34a9e564af2c23c19c63a957c5f8f88a146e78114e4ead605ec26e81436ba2467821b7bd80d86ffecdcd93bf8d2e4cb427696b5a08e064f7181d08005b72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
